<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css">
    <title>cadastro-carro</title>
</head>
<body>
<header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">Home</a>
        </nav>
    </header>

    <form>
    <div class="mx-auto col-12">
    <div class="form-group">
    <label >Modelo do carro</label>
    <input " class="form-control" name="modelo">
  </div>
  <div class="form-group">
    <label >Marca</label>
    <input class="form-control" name="marca">
  </div>
  <div class="form-group">
    <label >Ano</label>
    <input type="number" name="ano" class="form-control">
  </div>
  
  <button type="submit" class="btn btn-primary">Cadastrar</button>
  </div>
</form>



</body>
</html>