<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css">
    <title>Consulta</title>
</head>

<body>
<header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">Home</a>
        </nav>
    </header>

    <div class="container mt-5">

   <div class="row">
    <div class="col-12">
        <h1 class="text-center">Consultar Carro</h1>
    </div> 
    
    <div class="col-12"> 

        <table class="table table-dark">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Marca</th>
                    <th scope="col">Modelo</th>
                    <th scope="col">Ano</th>
                </tr>
            </thead>
            <tbody>
                <?php 
                foreach ($carro as $key => $value) {
                    echo'
                    <tr>
                        <th scope="row">'.$carro[$key]['id'].'</th>
                        <td>'.$carro[$key]['modelo'].'</td>
                        <td>'.$carro[$key]['marca'].'</td>
                        <td>'.$carro[$key]['ano'].'</td>
                    </tr>
                                     
                    ';
                }
                
                ?>
            </tbody>
        </table>

    </div>

   </div>



    </div>


</body>

</html>