<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">Home</a>
        </nav>
    </header>
        <div class="container mt-5">

            <section class="text-center">
                <div class="col-12">
                    <h1>Carros </h1>
                </div>

                <div class="mt-5 col-12 d-flex justify-content-around"> 
                    <a class="btn btn-secondary btn-lg" href="/cadastro-carro/">Cadastrar carro</a>
                    <a class="btn btn-primary btn-lg" href="/consultar/">Ver tabela de carros</a>
                    <a class="btn btn-secondary btn-lg" href="/editar/">Editar carros</a>

                </div>


            </section>
        </div>




</body>

</html>